lagom/lagom.github.io

build.sbt, src/main/scala/com/lightbend/lagom/docs/BlogMetaDataParser.scala, src/main/scala/com/lightbend/lagom/docs/DocumentationGenerator.scala
In this mode, if GitHub rate limits our API requests, we'll use a fallback. This should prevent rapid changes from blocking our ability to generate the site in development.
=> Introduce a "dev" mode

src/blog/lagom-1-2-1.md
Fix typo's:
- annoucen -> announce
- bug -> bugs
=> Fix typos in lagom 1.2.1 announcement post

src/main/assets/_documentation.styl
Fixes #24 
With these changes it's obvious when a code snippet is a link and when it's not.
=> Applies link style to code bits

build.sbt, src/main/scala/com/lightbend/lagom/docs/DocumentationGenerator.scala, src/main/twirl/com/lightbend/lagom/docs/main.scala.html
This will ensure when we move to CloudFlare that we can immediately deploy style updates without worrying about the CDN TTL.
=> Implemented asset finger printing

src/main/markdown/conduct.md
It was pointing to the Play mailing list.
=> Update the "contact owner" link

src/main/twirl/com/lightbend/lagom/docs/getstartedjava.scala.html
This also centers the getting started text above the buttons.
Request from @rstento 
Here's a screen shot of the result:
=> Remove duplicated text from the introduction

src/main/scala/com/lightbend/lagom/docs/DocumentationGenerator.scala, src/main/twirl/com/lightbend/lagom/docs/getstartedjava.scala.html, src/main/twirl/com/lightbend/lagom/docs/getstartedscala.scala.html
This might be easier to review commit-by-commit: I did a lot of reformatting, but I did all of the reformatting in separate commits from the other substantive changes.
=> Website fixes post 1.3.1 and 1.2.3

src/blog/microservices-from-development-to-production.md, src/main/scala/com/lightbend/lagom/docs/Blog.scala, src/main/scala/com/lightbend/lagom/docs/BlogMetaDataParser.scala
This avoids problems parsing UTF-8 characters on Windows and fixes #39.
Also improves the error reporting for blog metadata parsing failures to include the filename in the error output.
Finally, it strips offending characters from the problematic post.
Our Markdown renderer translates straight quotes to curly quotes and triple dots to ellipses anyway, so you can't tell the difference.
=> Enforce ASCII for blog posts

project/SimpleHTTPServer.scala
This adds support to serve one-folder-deep paths that won't include a filename (e.g. `/docs`) with a fallback to serving `index.html`.
Fixes #54 and also serves `/blog` (without trailing slash) which is also used in the site..
=> Support no-file path navigation in local execution

src/main/scala/com/lightbend/lagom/docs/DocumentationGenerator.scala, src/main/twirl/com/lightbend/lagom/docs/documentationIndex.scala.html
Reviews [Docs index](https://www.lagomframework.com/documentation/) to reduce the real estate used by versions/lang/api-docs and add a list of community provided contents.
Samples:
Before - 
After -
=> Reduce real estate used by versions. Adds community content

src/main/markdown/contributing.md
Also fix a few minor typos picked up by the IntelliJ spelling checker.
=> Update "Typesafe" to "Lightbend"

project/SimpleHTTPServer.scala, src/main/markdown/404.md
GitHub pages will serve a page called 404.html if it exists when pages aren't found. This adds that page, and also adds support to the built in dev server to serve it.
=> Added 404 page

src/main/twirl/com/lightbend/lagom/docs/getstartedjavasbt.scala.html, src/main/twirl/com/lightbend/lagom/docs/getstartedscala.scala.html
@TimMoore, I noticed the missing space in OSX on the two getting started pages I had revised, but then I found that Apple has been using macOS instead of OS X since 2016. Do we need to use both, since some users might have the older OS? or do you think macOS is sufficient? If it is, please merge this change to fix #88.
=> Change OSX to macOS.

src/main/twirl/com/lightbend/lagom/docs/getinvolved.scala.html
Changed community label from "[community](https://github.com/lagom/lagom/issues?q=label%3Acommunity)" to "[help:community](https://github.com/lagom/lagom/labels/help%3Acommunity)" and added new hyperlink of [newbie](https://github.com/lagom/lagom/labels/help%3Anewbie) label. I think it would be much easier for new contributors.
=> Change hyperlink of community label and add newbie label.

src/main/scala/com/lightbend/lagom/docs/DocumentationGenerator.scala
In my previous PR I forgot to update the link in the Docs index to `1.4.0-M2`
=> Increase version of preview to 1.4.0-M2

src/blog/lagom-1-4-0-M2.md
After discussing with @oliver we decided that despite the user profile on GH is all lowercase we'd post thanks with Capitalized names/surnames.
=> Capitalizes contributor name despite his profile on Github

src/main/twirl/com/lightbend/lagom/docs/getstartedjavamaven.scala.html, src/main/twirl/com/lightbend/lagom/docs/getstartedjavasbt.scala.html, src/main/twirl/com/lightbend/lagom/docs/getstartedscala.scala.html
There is currently a buggy redirect from http to https that changes the URL parameters and causes the resulting page to be empty.
=> Use https links to Tech Hub

src/blog/lagom-1-4-0-RC1.md, src/main/markdown/changelog.md, src/main/scala/com/lightbend/lagom/docs/DocumentationGenerator.scala
We forgot to add 1.4.0-RC1 as main stable release. 
This PR do the swap, but it keeps 1.3.10 as "current stable" and 1.4.0-RC1 as "current stable RC"
=> set 1.4.0-RC1 as main version

src/main/assets/_documentation.styl, src/main/assets/_vars.styl, src/main/twirl/com/lightbend/lagom/docs/documentation.scala.html
=> Add a cross-project search input

src/blog/lagom-1.4.5.md, src/main/scala/com/lightbend/lagom/docs/BlogMetaDataParser.scala, src/main/scala/com/lightbend/lagom/docs/DocumentationGenerator.scala, src/main/twirl/com/lightbend/lagom/docs/getstarted.scala.html
- Remove the changelog link from "Try Lagom" in favor of linking to milestones and commit logs
- Allow UTF-8 in blog posts, so we can spell Patrick Prémont's name correctly
=> Release 1.4.5

src/main/scala/com/lightbend/lagom/docs/DocumentationGenerator.scala, src/main/twirl/com/lightbend/lagom/docs/documentation.scala.html, src/main/twirl/com/lightbend/lagom/docs/documentationIndex.scala.html, src/main/twirl/com/lightbend/lagom/docs/documentationVersionIndex.scala.html
Changes the front page of the API documentation from the [blank-looking `root` package](https://www.lagomframework.com/documentation/1.4.x/scala/api/index.html) (requiring many clicks to navigate somewhere useful) to point to the [`com.lightbend.lagom.scaladsl`](https://www.lagomframework.com/documentation/1.4.x/scala/api/com/lightbend/lagom/scaladsl/index.html) package instead.
Thanks to @zbeckman for the suggestion!
=> Link Scala API doc to the scaladsl package

src/main/scala/com/lightbend/lagom/docs/DocumentationGenerator.scala, src/main/twirl/com/lightbend/lagom/docs/documentationIndex.scala.html
Adds community videos mentioned in #141 (not LB videos)
=> Adds videos (community only)

src/main/markdown/faq.md
I wasn't sure whether to update the question or remove it, so I went with the simpler option. WDYT? It's not such a frequently asked question these days (though now we do get some "Do I have to use Kubernetes?")
The only remaining references to ConductR on the site now are in docs for old versions, release announcements and other blog posts. Most of these are historical, so we don't need to update them. The only one I'm not sure about is https://www.lagomframework.com/blog/microservices-from-development-to-production.html @kwehden what do you think?
=> Remove FAQ item about ConductR

src/main/twirl/com/lightbend/lagom/docs/getinvolved.scala.html
- help:newbie is now "good first issue"
- help:community and help:needs-verification are now "help wanted"
These new labels match the GitHub conventions.
=> Update GitHub issue labels in "Get Involved"

src/main/public/.nojekyll
This is needed to publish the `.well-known/security.txt` file from #151, #154, and https://github.com/lightbend/vegemite/pull/5.
=> Disable Jekyll processing on GitHub Pages

src/blog/introducing-maven-support.md
This blog post appears as the top result from the Lagom web site when searching for "lagom maven" on Google. This might lead people to follow the instructions in the post and end up with an old version of the Maven archetype.
CC: @WadeWaldron
=> Add a link from the Maven announcement blog post to the Maven getting started guide

src/main/scala/com/lightbend/lagom/docs/DocumentationGenerator.scala
This looks like a change that was missing in the RC2 annoucment PR #173, comparing against the RC1 annoucment PR #167.
=> Trailing 1.5.0-RC2 change

src/blog/lagom-1-5-1-and-1-4-12.md
This is the announcement for 1.5.1 and 1.4.12 combo releases.
Links to changelog won't work because the tags don't exist yet. The list of contributors my also needs some adjustment after we cut the release.
Depends on https://github.com/lagom/lagom/pull/1883 and https://github.com/lagom/lagom/pull/1887
=> Releases 1.5.1 and 1.4.12

src/blog/lagom-1-5-0.md
Discussed with @theotown and this is no longer required. We hope this will improve search results for the 1.5.0 announcement.
=> Remove canonical reference from 1.5.0 blog

.mergify.yml
Reviewing why https://github.com/lagom/lagom.github.io/pull/213 was not merged by `mergify` I noticed https://github.com/lagom/lagom.github.io doesn’t have any CI job configured.
=> Remove Travis success check

.mergify.yml
I just realised that we don't need mergify here. There is no CI for the docs, so the reviewer either approve and merge it, or approve and let it wait to be merged later. 
That's exactly the case for PR #226. I want to approve it, but the release isn't done yet. So we want to wait for it. I almost approved and that would trigger the publication of the website.
=> Mergify: remove auto-merge

src/main/twirl/com/lightbend/lagom/docs/documentation.scala.html
Cross-index search is now more strict on the Algolia side. The JS implementation used to gather all the facets and index details and do a single HTTP request. With the new API verifications I guess we would need to send 3 separate requests.
To test this. Checkout the PR and use `sbt run`. Then open localhost:8080 and use the search functionality in the docs.
=> Disable cross-site search

src/main/assets/_base.styl, src/main/markdown/faq.md, src/main/twirl/com/lightbend/lagom/docs/blog.scala.html, src/main/twirl/com/lightbend/lagom/docs/getinvolved.scala.html, src/main/twirl/com/lightbend/lagom/docs/getstarted.scala.html, src/main/twirl/com/lightbend/lagom/docs/getstartedjava.scala.html, src/main/twirl/com/lightbend/lagom/docs/getstartedjavamaven.scala.html, src/main/twirl/com/lightbend/lagom/docs/getstartedjavasbt.scala.html, src/main/twirl/com/lightbend/lagom/docs/getstartedscala.scala.html, src/main/twirl/com/lightbend/lagom/docs/index.scala.html, src/main/twirl/com/lightbend/lagom/docs/lightbendBanner.scala.html, src/main/twirl/com/lightbend/lagom/docs/main.scala.html, src/main/twirl/com/lightbend/lagom/docs/markdown.scala.html, src/main/twirl/com/lightbend/lagom/docs/note.scala.html, src/main/twirl/com/lightbend/lagom/docs/support.scala.html, src/main/twirl/com/lightbend/lagom/docs/supportNote.scala.html, src/main/twirl/com/lightbend/lagom/docs/topNav.scala.html
- This adds EOL messaging to the site. 
- Removes links to Try Lagom. 
- Removes various references to support. 
See examples screenshots attached
=> udpate lagom site July 2023 - EOL messaging
