lagom/lagom.github.io

src/main/assets/_documentation.styl, src/main/assets/_social.styl, src/main/assets/_vars.styl, src/main/twirl/com/lightbend/lagom/docs/documentation.scala.html, src/main/twirl/com/lightbend/lagom/docs/download.scala.html, src/main/twirl/com/lightbend/lagom/docs/getinvolved.scala.html, src/main/twirl/com/lightbend/lagom/docs/index.scala.html, src/main/twirl/com/lightbend/lagom/docs/main.scala.html, src/main/twirl/com/lightbend/lagom/docs/markdown.scala.html, src/main/twirl/com/lightbend/lagom/docs/page.scala.html
Added Algolia search. Also ensured that when anchor links are navigated to, the sticky header doesn't cover the top of the anchor.
=> Added Algolia search

src/blog/microservices-from-development-to-production.md
Adding Christophers blog post about how to put microservices into production.
=> Adding Christophers blog post 

src/blog/lagom-1-2.md, src/main/assets/_base.styl, src/main/markdown/changelog.md, src/main/scala/com/lightbend/lagom/docs/DocumentationGenerator.scala, src/main/twirl/com/lightbend/lagom/docs/download.scala.html
- Update the docs and release version
- Blog post announcement
- Update the change log
- Link to the change log from the Download page
=> Release Lagom 1.2.0

src/main/twirl/com/lightbend/lagom/docs/getstartedscala.scala.html
This PR is blocked by https://github.com/lagom/lagom/pull/516.
Please @rstento review.
=> Updates link to latest page names

CONTRIBUTING.md
Adds CONTRIBUTING.md with details wrt lagom site being the sum of several sources. My intent was to provide pointers to the appropriate repos when contributors try to fox docs.
We should review the wording. Not sure we will be accepting contributions in this repo at all.
=> Adds CONTRIBUTING

src/main/assets/main.js, src/main/scala/com/lightbend/lagom/docs/DocumentationGenerator.scala, src/main/twirl/com/lightbend/lagom/docs/getstarted.scala.html, src/main/twirl/com/lightbend/lagom/docs/getstartedjava.scala.html, src/main/twirl/com/lightbend/lagom/docs/getstartedjavamaven.scala.html, src/main/twirl/com/lightbend/lagom/docs/getstartedjavasbt.scala.html, src/main/twirl/com/lightbend/lagom/docs/main.scala.html
Also:
* Removed scroll to code, which implemented smooth scrolling to anchor links, but didn't play well with the fixed position header.
* Ensured all getting started pages have a title
=> Get started AB test

src/main/scala/com/lightbend/lagom/docs/DocumentationGenerator.scala
=> Sort list of programming languages alphabetically to list java first

src/main/twirl/com/lightbend/lagom/docs/getstarted.scala.html, src/main/twirl/com/lightbend/lagom/docs/getstartedjava.scala.html, src/main/twirl/com/lightbend/lagom/docs/getstartedjavamaven.scala.html, src/main/twirl/com/lightbend/lagom/docs/getstartedjavasbt.scala.html, src/main/twirl/com/lightbend/lagom/docs/getstartedscala.scala.html, src/main/twirl/com/lightbend/lagom/docs/main.scala.html, src/main/twirl/com/lightbend/lagom/docs/topNav.scala.html
I was able to create a new experiment, so this PR has the correct experiment ID in it. Another minor change I made was to put the bulleted list of prerequisites after the intro sentences. It seemed awkward in the tests that the page started with the prereqs.
=> 57 rename nav button & try A/B test

src/main/twirl/com/lightbend/lagom/docs/getstartedjavamaven.scala.html, src/main/twirl/com/lightbend/lagom/docs/getstartedjavasbt.scala.html, src/main/twirl/com/lightbend/lagom/docs/getstartedscala.scala.html
And, the information that creating the project and running it will take a bit of time. Fixes issue #56.
=> Added the version to the sbt command

src/main/twirl/com/lightbend/lagom/docs/getstartedjavasbt.scala.html, src/main/twirl/com/lightbend/lagom/docs/getstartedscala.scala.html
Fixes https://github.com/lagom/lagom/issues/683
=> Add support for HTTPS on seed-based project creation

src/main/scala/com/lightbend/lagom/docs/DocumentationGenerator.scala
Include Knoldus' wrt circuit breaker
Include MBernhardt's series on lagom
=> Adds recent blog post links

src/blog/lagom-1-4-0-M1.md, src/main/markdown/changelog.md, src/main/scala/com/lightbend/lagom/docs/DocumentationGenerator.scala
Adds blog announcement and changelog
Fixes #77
=> Prepares release notes 140 m1

src/main/twirl/com/lightbend/lagom/docs/documentationIndex.scala.html, src/main/twirl/com/lightbend/lagom/docs/getstarted.scala.html, src/main/twirl/com/lightbend/lagom/docs/index.scala.html
=> A few tweaks to title meta tags

src/main/twirl/com/lightbend/lagom/docs/getstartedscala.scala.html
Simplified the flow. Please check carefully because I was not able to build and test locally. Still looking into it.
Fixes #78
=> Updated Getting Started flow for Scala

src/blog/lagom-1-3-6.md
Incorporates feedback from @rstento in #86.
=> Improve the Lagom 1.3.6 announcement post

src/main/twirl/com/lightbend/lagom/docs/getstarted.scala.html, src/main/twirl/com/lightbend/lagom/docs/getstartedjavamaven.scala.html
=> Fixing instructions to use Tech Hub.

src/main/twirl/com/lightbend/lagom/docs/getstartedjavamaven.scala.html
=> Changes version in link to @context.currentDocsVersion

src/blog/lagom-1-3-9.md, src/main/markdown/changelog.md, src/main/scala/com/lightbend/lagom/docs/DocumentationGenerator.scala
=> 1.3.9 release

src/main/twirl/com/lightbend/lagom/docs/index.scala.html
Since ConductR isn't available to new customers or for eval purposes, I was asked by Sales to remove this video.
=> Commented out the ConductR video with a note as to why

src/main/twirl/com/lightbend/lagom/docs/getstartedjavamaven.scala.html
=> fixes maven command call in get started guide

src/blog/lagom-1-4-0.md, src/main/markdown/changelog-1.3.x.md, src/main/markdown/changelog-archive.md, src/main/markdown/changelog.md, src/main/scala/com/lightbend/lagom/docs/DocumentationGenerator.scala
Still needs some final changelog/author updates after the last few merges.
=> 1.4.0 release announcement

src/main/scala/com/lightbend/lagom/docs/DocumentationGenerator.scala
A rather long workshop to go from zero to hero in ES using Lagom
=> Adds link to Inviqa's post on ES

src/blog/announcing-discuss-lagomframework-forum.md, src/blog/announcing-lagom-recipes.md, src/main/assets/_social.styl, src/main/markdown/conduct.md, src/main/markdown/faq.md, src/main/twirl/com/lightbend/lagom/docs/getinvolved.scala.html, src/main/twirl/com/lightbend/lagom/docs/main.scala.html, src/main/twirl/com/lightbend/lagom/docs/support.scala.html
- Add a blog post with an introduction
- Change all mailing list links to the new forum
- Fix small typos and other issues on the affected pages
=> Announce discuss.lagomframework.com

src/blog/event-sourcing-vs-crud.md
Thanks @jibbers42 for pointing this out!
=> Fixes video link

src/blog/microservices-from-development-to-production.md
=> Link to Lightbend Orchestration from the ConductR blog post

src/blog/lagom-1.4.6.md, src/main/scala/com/lightbend/lagom/docs/DocumentationGenerator.scala
=> Release 1.4.6

src/main/scala/com/lightbend/lagom/docs/DocumentationGenerator.scala, src/main/twirl/com/lightbend/lagom/docs/documentation.scala.html
=> Fix extra space in version selector

src/main/public/.well-known/security.txt
=> Added security.txt

build.sbt
=> Include all dot files

src/main/twirl/com/lightbend/lagom/docs/getstartedjavasbt.scala.html, src/main/twirl/com/lightbend/lagom/docs/getstartedscala.scala.html
=> Update getting started guides to recommend sbt 1.2.1

src/main/scala/com/lightbend/lagom/docs/DocumentationGenerator.scala
(second attempt)
related to https://github.com/lagom/lagom.github.io/pull/162
=> Fixes preview links in docs index page

src/blog/lagom-1-5-0-RC2.md
Only merge after completing https://github.com/playframework/play-meta/issues/45
=> Announce release 1.5.0-RC2

src/main/scala/com/lightbend/lagom/docs/DocumentationGenerator.scala
=> Point 1.5.0-RC2 to the correct branch

src/main/scala/com/lightbend/lagom/docs/DocumentationGenerator.scala
Part of https://github.com/playframework/play-meta/issues/84.
=> Lagm 1.6.0-M2

build.sbt, src/main/scala/com/lightbend/lagom/docs/BlogMetaDataParser.scala, src/main/scala/com/lightbend/lagom/docs/DocumentationGenerator.scala
- Update Lightbend Markdown to latest release (1.7.0).
- Update Scala to 2.12.9 (2.13 support has not been released yet for
Lightbend Markdown).
- Fix Logger deprecation warnings.
- Fix type erasure warnings in YAML parser.
=> Miscellaneous build updates

src/main/markdown/faq.md
- Fix some spelling
- Fix link to Lightbend Platform
- Add link docs on how to disable embedded Kafka server
=> Some small fixes/improvements on FAQ

src/main/twirl/com/lightbend/lagom/docs/main.scala.html
=> removes Scoop it
